export const mockItemsDatabase = {
  Chinese: [
    { name: 'Ajinomoto', balance: "" },
    { name: 'Baking PWD', balance: "" },
    { name: 'Bbq Sauce', balance: "" },
    { name: 'Coconut Milk PWD', balance: "" },
    { name: 'Cocking Wine', balance: "" },
    { name: 'Corn Flor', balance: "" },
    { name: 'Dark Soy Sauce', balance: "" },
    { name: 'Degi Mirch PWD', balance: "" },
    { name: 'DUSTAR', balance: "" },
    { name: 'GINGER PICKLE', balance: "" },
    { name: 'HONEY', balance: "" },
    { name: 'KIKOMAN SAUCE', balance: "" },
    { name: 'LIGHT SOYA SAUCE', balance: "" },
    { name: 'MUSTARD SEEDS', balance: "" },
    { name: 'NORI SHEET', balance: "" },
    { name: 'OYESTER SAUCE', balance: "" },
    { name: 'POCHA', balance: "" },
    { name: 'PATATO STARCH', balance: "" },
    { name: 'WHEAT STARCH', balance: "" },
    { name: 'RED CHILLI WHOLE', balance: "" },
    { name: 'REFINED OIL', balance: "" },
    { name: 'SALT', balance: "" },
    { name: 'SESEMI OIL', balance: "" },
    { name: 'SESAMI SEEDS', balance: "" },
    { name: 'SUSHI RICE', balance: "" },
    { name: 'TEMPURA FLOUR', balance: "" },
    { name: 'TAMATO KETCHUP', balance: "" },
    { name: 'VINIGER', balance: "" },
    { name: 'WHITE PEPER PWD', balance: "" }
  ],
  Indian: [
    { name: 'AJWINE', balance: "" },
    { name: 'ARHAR DAL', balance: "" },
    { name: 'BADAM', balance: "" },
    { name: 'BASMATI RICE', balance: "" },
    { name: 'BESAN', balance: "" },
    { name: 'CHANA DAL', balance: "" },
    { name: 'COFFEE', balance: "" },
    { name: 'DALCHINI', balance: "" },
    { name: 'DUSTAR', balance: "" },
    { name: 'DEGI MIRCH PWD', balance: "" },
    { name: 'DESI GHEE', balance: "" },
    { name: 'DHANIYA PWD', balance: "" },
    { name: 'GOLDEN SILLA RICE', balance: "" },
    { name: 'GUD', balance: "" },
    { name: 'GULAB JAL', balance: "" },
    { name: 'KAJU', balance: "" },
    { name: 'KEWRA JAL', balance: "" },
    { name: 'KISMISH', balance: "" },
    { name: 'MAGAJ', balance: "" },
    { name: 'PEANUT', balance: "" },
    { name: 'PAPAD', balance: "" },
    { name: 'PINEAPPLE SLICE', balance: "" },
    { name: 'TEA', balance: "" },
    { name: 'MAKHANE', balance: "" },
    { name: 'URAD DAL', balance: "" },
    { name: 'STAFF RICE', balance: "" },
    { name: 'BLACK MASOOR DAL', balance: "" },
    { name: 'VINIGER', balance: "" },
    { name: 'TAMATO PUREE', balance: "" },
    { name: 'DHANIYA WHOLE', balance: "" },
    { name: 'ELACHI BIG', balance: "" },
    { name: 'ELACHI GREEN', balance: "" },
    { name: 'GARAM MASALA', balance: "" },
    { name: 'HALDI PWD', balance: "" },
    { name: 'JABITRI', balance: "" },
    { name: 'JEERA PWD', balance: "" },
    { name: 'JEERA WHOLE', balance: "" },
    { name: 'KASTURI METHI', balance: "" },
    { name: 'KITCHEN KING', balance: "" },
    { name: 'LONG', balance: "" },
    { name: 'MEAT MASALA', balance: "" },
    { name: 'SALT', balance: "" },
    { name: 'SOUF', balance: "" },
    { name: 'TEJ PATTA', balance: "" },
    { name: 'NAPKIN', balance: "" },
    { name: 'RAJMA', balance: "" },
    { name: 'MIX DAL', balance: "" },
    { name: 'KABULI CHANA', balance: "" },
    { name: 'SOYA BADI', balance: "" }
  ],
  Continental: [
    { name: 'BADAM', balance: "" },
    { name: 'BLACK OLIVE', balance: "" },
    { name: 'BLACK PEPER', balance: "" },
    { name: 'BREAD CRUMS', balance: "" },
    { name: 'BROTH CHICKEN PWD', balance: "" },
    { name: 'CAJUN SPICE', balance: "" },
    { name: 'CAPER', balance: "" },
    { name: 'CHEESE SAUSE', balance: "" },
    { name: 'CHILLI FLEX', balance: "" },
    { name: 'CHOCOLATE SAUCE', balance: "" },
    { name: 'DEMI GLAZE', balance: "" },
    { name: 'DUSTAR', balance: "" },
    { name: 'GARLIC PWD', balance: "" },
    { name: 'JALAPINO SLICE', balance: "" },
    { name: 'KABULI CHANA', balance: "" },
    { name: 'LASANGA SGEET', balance: "" },
    { name: 'MAYONISE', balance: "" },
    { name: 'MUSTARD SAUCE', balance: "" },
    { name: 'NACHOS', balance: "" },
    { name: 'OREGANO', balance: "" },
    { name: 'PENNE PASTA', balance: "" },
    { name: 'PINEAPPLE SLICE', balance: "" },
    { name: 'PERI PERI PWD', balance: "" },
    { name: 'SAMAC PWD', balance: "" },
    { name: 'SPAGHETTI PASTA', balance: "" },
    { name: 'TACOS', balance: "" },
    { name: 'TAHINA PASTE', balance: "" },
    { name: 'TAMATO PILATE', balance: "" },
    { name: 'TAMATO PUREE', balance: "" },
    { name: 'SUJI', balance: "" },
    { name: 'SILVER ONION', balance: "" }
  ],
  Tandoor: [
    { name: 'AATA', balance: "" },
    { name: 'MAIDA', balance: "" },
    { name: 'CHAT MASALA', balance: "" },
    { name: 'KAJU', balance: "" },
    { name: 'BADAM', balance: "" },
    { name: 'DUSTAR', balance: "" },
    { name: 'MUSTERD OIL', balance: "" },
    { name: 'BLACK SALT', balance: "" },
    { name: 'GARAM MASALA', balance: "" },
    { name: 'KITCHEN KING', balance: "" },
    { name: 'DEGI MIRCH PWD', balance: "" },
    { name: 'JEERA WHOLE', balance: "" },
    { name: 'JEERA PWD', balance: "" },
    { name: 'DHANIYA WHOLE', balance: "" },
    { name: 'DHANIYA PWD', balance: "" },
    { name: 'BUTCHERY BAG', balance: "" },
    { name: 'CLENING FOIL', balance: "" },
    { name: 'SILVER FOIL', balance: "" },
    { name: 'ROTI ENVOLPE', balance: "" },
    { name: 'GREEN ELICHI', balance: "" },
    { name: 'GARBAGE BAG BIG', balance: "" },
    { name: 'POCHA', balance: "" },
    { name: 'SURF', balance: "" },
    { name: 'JUNA STEEL', balance: "" },
    { name: 'NAPKIN', balance: "" },
    { name: 'BESAN', balance: "" },
    { name: 'YELLOW CHIILI PWD', balance: "" }
  ]
};
