export const mockItemsDatabase = {
  Chinese: [
    { name: 'Ajinomoto', balance: "" },
    { name: 'Baking Powder', balance: "" },
    { name: 'BBQ Sauce', balance: "" },
    { name: 'Coconut Milk Powder', balance: "" },
    { name: 'Cooking Wine', balance: "" },
    { name: 'Corn Flour', balance: "" },
    { name: 'Dark Soy Sauce', balance: "" },
    { name: 'Degi Mirch Powder', balance: "" },
    { name: 'Dustar', balance: "" },
    { name: 'Ginger Pickle', balance: "" },
    { name: 'Honey', balance: "" },
    { name: 'Kikkoman Sauce', balance: "" },
    { name: 'Light Soy Sauce', balance: "" },
    { name: 'Mustard Seeds', balance: "" },
    { name: 'Nori Sheet', balance: "" },
    { name: 'Oyster Sauce', balance: "" },
    { name: 'Pocha', balance: "" },
    { name: 'Potato Starch', balance: "" },
    { name: 'Wheat Starch', balance: "" },
    { name: 'Red Chilli Whole', balance: "" },
    { name: 'Refined Oil', balance: "" },
    { name: 'Salt', balance: "" },
    { name: 'Sesame Oil', balance: "" },
    { name: 'Sesame Seeds', balance: "" },
    { name: 'Sushi Rice', balance: "" },
    { name: 'Tempura Flour', balance: "" },
    { name: 'Tomato Ketchup', balance: "" },
    { name: 'Vinegar', balance: "" },
    { name: 'White Pepper Powder', balance: "" }
  ],
  Indian: [
    { name: 'Ajwain', balance: "" },
    { name: 'Arhar Dal', balance: "" },
    { name: 'Badam', balance: "" },
    { name: 'Basmati Rice', balance: "" },
    { name: 'Besan', balance: "" },
    { name: 'Chana Dal', balance: "" },
    { name: 'Coffee', balance: "" },
    { name: 'Dalchini', balance: "" },
    { name: 'Dustar', balance: "" },
    { name: 'Degi Mirch Powder', balance: "" },
    { name: 'Desi Ghee', balance: "" },
    { name: 'Dhaniya Powder', balance: "" },
    { name: 'Golden Sella Rice', balance: "" },
    { name: 'Gud', balance: "" },
    { name: 'Gulab Jal', balance: "" },
    { name: 'Kaju', balance: "" },
    { name: 'Kewra Jal', balance: "" },
    { name: 'Kismis', balance: "" },
    { name: 'Magaj', balance: "" },
    { name: 'Peanut', balance: "" },
    { name: 'Papad', balance: "" },
    { name: 'Pineapple Slice', balance: "" },
    { name: 'Tea', balance: "" },
    { name: 'Makhane', balance: "" },
    { name: 'Urad Dal', balance: "" },
    { name: 'Staff Rice', balance: "" },
    { name: 'Black Masoor Dal', balance: "" },
    { name: 'Vinegar', balance: "" },
    { name: 'Tomato Puree', balance: "" },
    { name: 'Dhaniya Whole', balance: "" },
    { name: 'Elaichi Big', balance: "" },
    { name: 'Elaichi Green', balance: "" },
    { name: 'Garam Masala', balance: "" },
    { name: 'Haldi Powder', balance: "" },
    { name: 'Javitri', balance: "" },
    { name: 'Jeera Powder', balance: "" },
    { name: 'Jeera Whole', balance: "" },
    { name: 'Kasuri Methi', balance: "" },
    { name: 'Kitchen King', balance: "" },
    { name: 'Laung', balance: "" },
    { name: 'Meat Masala', balance: "" },
    { name: 'Salt', balance: "" },
    { name: 'Saunf', balance: "" },
    { name: 'Tej Patta', balance: "" },
    { name: 'Napkin', balance: "" },
    { name: 'Rajma', balance: "" },
    { name: 'Mix Dal', balance: "" },
    { name: 'Kabuli Chana', balance: "" },
    { name: 'Soya Badi', balance: "" }
  ],
  Continental: [
    { name: 'Badam', balance: "" },
    { name: 'Black Olive', balance: "" },
    { name: 'Black Pepper', balance: "" },
    { name: 'Bread Crumbs', balance: "" },
    { name: 'Chicken Broth Powder', balance: "" },
    { name: 'Cajun Spice', balance: "" },
    { name: 'Capers', balance: "" },
    { name: 'Cheese Sauce', balance: "" },
    { name: 'Chilli Flakes', balance: "" },
    { name: 'Chocolate Sauce', balance: "" },
    { name: 'Demi Glace', balance: "" },
    { name: 'Dustar', balance: "" },
    { name: 'Garlic Powder', balance: "" },
    { name: 'Jalapeno Slices', balance: "" },
    { name: 'Kabuli Chana', balance: "" },
    { name: 'Lasagna Sheet', balance: "" },
    { name: 'Mayonnaise', balance: "" },
    { name: 'Mustard Sauce', balance: "" },
    { name: 'Nachos', balance: "" },
    { name: 'Oregano', balance: "" },
    { name: 'Penne Pasta', balance: "" },
    { name: 'Pineapple Slice', balance: "" },
    { name: 'Peri Peri Powder', balance: "" },
    { name: 'Sumac Powder', balance: "" },
    { name: 'Spaghetti Pasta', balance: "" },
    { name: 'Tacos', balance: "" },
    { name: 'Tahini Paste', balance: "" },
    { name: 'Tomato Paste', balance: "" },
    { name: 'Tomato Puree', balance: "" },
    { name: 'Suji', balance: "" },
    { name: 'Silver Onion', balance: "" }
  ],
  Tandoor: [
    { name: 'Atta', balance: "" },
    { name: 'Maida', balance: "" },
    { name: 'Chat Masala', balance: "" },
    { name: 'Kaju', balance: "" },
    { name: 'Badam', balance: "" },
    { name: 'Dustar', balance: "" },
    { name: 'Mustard Oil', balance: "" },
    { name: 'Black Salt', balance: "" },
    { name: 'Garam Masala', balance: "" },
    { name: 'Kitchen King', balance: "" },
    { name: 'Degi Mirch Powder', balance: "" },
    { name: 'Jeera Whole', balance: "" },
    { name: 'Jeera Powder', balance: "" },
    { name: 'Dhaniya Whole', balance: "" },
    { name: 'Dhaniya Powder', balance: "" },
    { name: 'Butchery Bag', balance: "" },
    { name: 'Cleaning Foil', balance: "" },
    { name: 'Silver Foil', balance: "" },
    { name: 'Roti Envelope', balance: "" },
    { name: 'Green Elaichi', balance: "" },
    { name: 'Garbage Bag Big', balance: "" },
    { name: 'Pocha', balance: "" },
    { name: 'Surf', balance: "" },
    { name: 'Juna Steel', balance: "" },
    { name: 'Napkin', balance: "" },
    { name: 'Besan', balance: "" },
    { name: 'Yellow Chilli Powder', balance: "" }
  ]
};
